Repository Block-Guard/BlockGuard-AI, pull requests merged in 2025-08, with the labels that each got.

#11 [Feat] 점수화 로직 추가
  .gitignore
  app/models/fraud_response.py
  app/prompts/data/fraud_examples.py
  app/prompts/data/score_rules.txt
  app/prompts/fraud_example.py
  app/prompts/fraud_prompts.py
  app/services/gpt_service.py
Labels: 🚀 Feature, 🐼 채유

#13 [Feat] Gpt prompt tuning
  app/models/fraud_response.py
  app/prompts/data/fraud_examples.py
  app/prompts/data/score_rules.txt
  app/prompts/fraud_prompts.py
Labels: 🐶 연주, 🐼 채유, ➕ Refactor

#15 [Fix] 사기분석 API 응답 keywords 필드 빈 리스트 허용
  app/models/fraud_response.py
Labels: 🐞 BugFix, 🐶 연주
